name: Build

# Put your personal access token in a repository secret named PAT for cross-repository access


on:
  workflow_dispatch:
  inputs:
    release_type:
      required: true
      type: choice
      options:
      - patch
      - minor
      - major
  push:
    branches:
      - main

env:
  INTERNAL_NAME: InventorySorting
  CONFIGURATION: Release
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
      - name: Update changelog
        id: update-changelog
        uses: release-flow/keep-a-changelog-action@v2 
        with:
          command: bump
          version: ${{ github.event.inputs.release-type }}
      - name: Restore
        run: dotnet restore -r win
      - name: Build
        run: dotnet build -c ${{ env.CONFIGURATION }} --no-restore ${{ env.INTERNAL_NAME }}
      - name: Push artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            InventorySorting/bin/Release/InventorySorting/latest.zip
          compression-level: 0
